DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS location;

CREATE TABLE location (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(255), 
description TEXT,
PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE product (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(255), 
description TEXT,
location_id INT(11),
price FLOAT,
qty_on_hand INT,
PRIMARY KEY (id),
FOREIGN KEY (location_id) REFERENCES location(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE customer (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(255), 
address VARCHAR(255),
phone VARCHAR(255),
email VARCHAR(255),
PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE cart_status (
id INT(11) NOT NULL AUTO_INCREMENT, 
name VARCHAR(255),
PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE cart (
id INT(11) NOT NULL AUTO_INCREMENT,
customer_id INT(11), 
cart_status_id INT(11),
PRIMARY KEY (id),
FOREIGN KEY (customer_id) REFERENCES customer(id) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY (cart_status_id) REFERENCES cart_status(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE cart_contents (
cart_id INT(11),
product_id INT(11),
product_qty INT(11) NOT NULL,
FOREIGN KEY (cart_id) REFERENCES cart(id) ON UPDATE CASCADE ON DELETE CASCADE, 
FOREIGN KEY (product_id) REFERENCES product(id) ON UPDATE CASCADE ON DELETE RESTRICT 
) ENGINE=InnoDB;

CREATE TABLE shipment (
id INT(11) NOT NULL AUTO_INCREMENT,
cart_id INT(11), 
location_id INT(11), 
PRIMARY KEY (id),
FOREIGN KEY (cart_id) REFERENCES cart(id) ON UPDATE CASCADE ON DELETE RESTRICT, 
FOREIGN KEY (location_id) REFERENCES location(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;
